#!/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#for i in $(bspc query -D --names)
#do
    #bsp-layout set tall $i -- --master-size 0.65 &
#done

bspc config border_width         2
bspc config focused_border_color "#FA74B2"
bspc config normal_border_color "#282e3a"

ln -s $WALLPAPERS/nord-theme $HOME/.config/GIMP/2.10/splashes

xfce4-power-manager &

#copyq &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#gnome key-ring
gnome-keyring-daemon --login --unlock --replace ---daemonize --components=ssh &

# gammastep
gammastep-indicator -l 10:107 &

# change brightness
brightnessctl s 50% &

# Networking tray icon
nm-applet &
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
xautolock -time 15 -locker "/home/$USER/.config/i3/scripts/lock.sh" &
xautolock -time 30 -locker "/home/$USER/.config/i3/scripts/lock.sh && systemctl suspend" &
#$HOME/.config/bspwm/bspborders &
$HOME/.scripts/autostart.bspwm
